//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLHighlandsCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangChamCong
    {
        public string MaNV { get; set; }
        public string MaCLV { get; set; }
        public string TenNV { get; set; }
        public System.DateTime NgayLam { get; set; }
        public double GioVao { get; set; }
        public double GioRa { get; set; }
        /* public Nullable<double> Cong { get; set; }*/
        public double Cong { get; set; }
        public virtual CaLamViec CaLamViec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
