//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLHighlandsCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaHoaDon { get; set; }
        public string MaHang { get; set; }
        public string Size { get; set; }
        public int SoLuong { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual HangBan HangBan { get; set; }
    }
}
