//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLHighlandsCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatHang
    {
        public int MaDDH { get; set; }
        public string MaNL { get; set; }
        public int SoLuongNhap { get; set; }
    
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
