//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTLHighlandsCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public string MaNV { get; set; }
        public string MaCLV { get; set; }
        public Nullable<double> NgayCong { get; set; }
        public Nullable<double> Thuong { get; set; }
        public Nullable<double> TongLuong { get; set; }
        public Nullable<double> TamUng { get; set; }
        public string LuongThang { get; set; }
        public string LuongNam { get; set; }
    
        public virtual CaLamViec CaLamViec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
